// 샘플 보안 채용 공고 데이터
window.JOB_DATA = [
  {
    id: 1,
    company: "토스",
    companyShort: "T",
    logoColor: "#0064FF",
    title: "Security Engineer (Application Security)",
    domain: "보안 엔지니어링",
    domainEn: "AppSec",
    experience: "경력 5년 이상",
    expYears: 5,
    location: "서울 강남구",
    remote: "하이브리드",
    salary: "8,000 - 1.2억",
    salaryNum: 10000,
    deadline: "2026-05-08",
    dday: 12,
    source: "원티드",
    posted: "2026-04-22",
    isNew: true,
    tags: ["AppSec", "SDLC", "Threat Modeling"],
  },
  {
    id: 2,
    company: "쿠팡",
    companyShort: "C",
    logoColor: "#F03A47",
    title: "Senior Cloud Security Architect",
    domain: "클라우드 보안",
    domainEn: "Cloud",
    experience: "경력 8년 이상",
    expYears: 8,
    location: "서울 송파구",
    remote: "출근",
    salary: "협의",
    salaryNum: 13000,
    deadline: "2026-05-02",
    dday: 6,
    source: "LinkedIn",
    posted: "2026-04-15",
    isNew: false,
    tags: ["AWS", "GCP", "Zero Trust"],
  },
  {
    id: 3,
    company: "네이버클라우드",
    companyShort: "N",
    logoColor: "#03C75A",
    title: "정보보안 컨설턴트 (ISMS-P)",
    domain: "정보보안",
    domainEn: "GRC",
    experience: "경력 7년 이상",
    expYears: 7,
    location: "성남 분당구",
    remote: "하이브리드",
    salary: "7,500 - 1억",
    salaryNum: 8750,
    deadline: "2026-04-30",
    dday: 4,
    source: "잡코리아",
    posted: "2026-04-18",
    isNew: false,
    tags: ["ISMS-P", "ISO27001", "컴플라이언스"],
  },
  {
    id: 4,
    company: "카카오뱅크",
    companyShort: "K",
    logoColor: "#FFE94E",
    logoText: "#191919",
    title: "SecOps Lead Engineer",
    domain: "SecOps",
    domainEn: "SecOps",
    experience: "경력 6년 이상",
    expYears: 6,
    location: "서울 영등포구",
    remote: "원격 가능",
    salary: "9,000 - 1.3억",
    salaryNum: 11000,
    deadline: "2026-05-15",
    dday: 19,
    source: "원티드",
    posted: "2026-04-23",
    isNew: true,
    tags: ["SIEM", "SOAR", "Incident Response"],
  },
  {
    id: 5,
    company: "당근",
    companyShort: "D",
    logoColor: "#FF7E36",
    title: "Senior Security Engineer",
    domain: "보안 엔지니어링",
    domainEn: "SecEng",
    experience: "경력 5년 이상",
    expYears: 5,
    location: "서울 강남구",
    remote: "하이브리드",
    salary: "협의",
    salaryNum: 9500,
    deadline: "2026-05-20",
    dday: 24,
    source: "회사 채용 페이지",
    posted: "2026-04-20",
    isNew: false,
    tags: ["IAM", "Kubernetes", "DevSecOps"],
  },
  {
    id: 6,
    company: "삼성SDS",
    companyShort: "S",
    logoColor: "#1428A0",
    title: "클라우드 보안 아키텍트",
    domain: "클라우드 보안",
    domainEn: "Cloud",
    experience: "경력 10년 이상",
    expYears: 10,
    location: "서울 송파구",
    remote: "출근",
    salary: "1.1억 - 1.5억",
    salaryNum: 13000,
    deadline: "2026-04-29",
    dday: 3,
    source: "잡코리아",
    posted: "2026-04-10",
    isNew: false,
    tags: ["Hybrid Cloud", "CSPM", "거버넌스"],
  },
  {
    id: 7,
    company: "라인",
    companyShort: "L",
    logoColor: "#06C755",
    title: "Principal Security Engineer",
    domain: "보안 엔지니어링",
    domainEn: "SecEng",
    experience: "경력 9년 이상",
    expYears: 9,
    location: "서울 강남구",
    remote: "하이브리드",
    salary: "1.2억 - 1.8억",
    salaryNum: 15000,
    deadline: "2026-05-25",
    dday: 29,
    source: "LinkedIn",
    posted: "2026-04-24",
    isNew: true,
    tags: ["Cryptography", "Mobile Security", "Architecture"],
  },
  {
    id: 8,
    company: "우아한형제들",
    companyShort: "B",
    logoColor: "#2AC1BC",
    title: "정보보안 관리자 (Security GRC)",
    domain: "정보보안",
    domainEn: "GRC",
    experience: "경력 6년 이상",
    expYears: 6,
    location: "서울 송파구",
    remote: "하이브리드",
    salary: "7,000 - 9,500",
    salaryNum: 8250,
    deadline: "2026-05-10",
    dday: 14,
    source: "원티드",
    posted: "2026-04-21",
    isNew: false,
    tags: ["GRC", "위험관리", "내부통제"],
  },
  {
    id: 9,
    company: "SK쉴더스",
    companyShort: "SK",
    logoColor: "#EA002C",
    title: "Cloud Security Engineer (AWS Specialist)",
    domain: "클라우드 보안",
    domainEn: "Cloud",
    experience: "경력 5년 이상",
    expYears: 5,
    location: "서울 종로구",
    remote: "출근",
    salary: "8,000 - 1.1억",
    salaryNum: 9500,
    deadline: "2026-05-05",
    dday: 9,
    source: "사람인",
    posted: "2026-04-17",
    isNew: false,
    tags: ["AWS", "Terraform", "Container Security"],
  },
  {
    id: 10,
    company: "야놀자",
    companyShort: "Y",
    logoColor: "#E4007F",
    title: "Senior SecOps Engineer",
    domain: "SecOps",
    domainEn: "SecOps",
    experience: "경력 7년 이상",
    expYears: 7,
    location: "서울 강남구",
    remote: "원격 가능",
    salary: "협의",
    salaryNum: 10500,
    deadline: "2026-05-12",
    dday: 16,
    source: "원티드",
    posted: "2026-04-19",
    isNew: false,
    tags: ["EDR", "Threat Hunting", "Detection Engineering"],
  },
  {
    id: 11,
    company: "직방",
    companyShort: "Z",
    logoColor: "#FF7800",
    title: "보안 엔지니어 (Lead)",
    domain: "보안 엔지니어링",
    domainEn: "SecEng",
    experience: "경력 8년 이상",
    expYears: 8,
    location: "서울 서초구",
    remote: "하이브리드",
    salary: "1억 - 1.4억",
    salaryNum: 12000,
    deadline: "2026-05-18",
    dday: 22,
    source: "잡플래닛",
    posted: "2026-04-22",
    isNew: true,
    tags: ["Security Architecture", "Pentest", "Bug Bounty"],
  },
  {
    id: 12,
    company: "11번가",
    companyShort: "11",
    logoColor: "#FF0038",
    title: "정보보안팀 시니어 (ISMS)",
    domain: "정보보안",
    domainEn: "GRC",
    experience: "경력 9년 이상",
    expYears: 9,
    location: "서울 중구",
    remote: "출근",
    salary: "9,500 - 1.3억",
    salaryNum: 11250,
    deadline: "2026-04-28",
    dday: 2,
    source: "잡코리아",
    posted: "2026-04-08",
    isNew: false,
    tags: ["ISMS", "PCI-DSS", "감사대응"],
  },
  {
    id: 13,
    company: "리디",
    companyShort: "R",
    logoColor: "#1F8CE6",
    title: "Cloud Security Engineer",
    domain: "클라우드 보안",
    domainEn: "Cloud",
    experience: "경력 5년 이상",
    expYears: 5,
    location: "서울 강남구",
    remote: "원격 가능",
    salary: "8,500 - 1.1억",
    salaryNum: 9750,
    deadline: "2026-05-30",
    dday: 34,
    source: "원티드",
    posted: "2026-04-25",
    isNew: true,
    tags: ["AWS", "GCP", "IaC"],
  },
  {
    id: 14,
    company: "마켓컬리",
    companyShort: "M",
    logoColor: "#5F0080",
    title: "Senior DevSecOps Engineer",
    domain: "SecOps",
    domainEn: "DevSecOps",
    experience: "경력 6년 이상",
    expYears: 6,
    location: "서울 강남구",
    remote: "하이브리드",
    salary: "8,500 - 1.2억",
    salaryNum: 10250,
    deadline: "2026-05-14",
    dday: 18,
    source: "원티드",
    posted: "2026-04-20",
    isNew: false,
    tags: ["CI/CD", "SAST/DAST", "Container"],
  },
  {
    id: 15,
    company: "안랩",
    companyShort: "A",
    logoColor: "#1A4789",
    title: "Lead Security Researcher",
    domain: "보안 엔지니어링",
    domainEn: "Research",
    experience: "경력 10년 이상",
    expYears: 10,
    location: "성남 분당구",
    remote: "출근",
    salary: "1.1억 - 1.6억",
    salaryNum: 13500,
    deadline: "2026-05-22",
    dday: 26,
    source: "회사 채용 페이지",
    posted: "2026-04-23",
    isNew: true,
    tags: ["Vulnerability Research", "Reverse Engineering", "Exploit"],
  },
];
